name: CI

on: [push]

jobs:
  build:
    name: Run tests and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Use Node 10
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Build and test
        run: yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true
